return {
    misc={
        dictionary = {
            k_debugplus1 = "While in collection, hover over a card",
            k_debugplus2 = "and press the following keys:",
            k_debugplus3 = "[1] Unlock",
            k_debugplus4 = "[2] Discover",
            k_debugplus5 = "[3] Spawn",
            k_debugplus6 = "Hover over any Joker/Playing card",
            k_debugplus7 = "hold Ctrl (togglable in config)",
            k_debugplus8 = "and press [Q] to cycle Edition",
            k_debugplus9 = "press [W] to cycle Enhancement",
            k_debugplus10 = "press [E] to cycle Seal",
            k_debugplus11 = "press [A/S/D] to toggle Eternal/Perishable/Rental",
            k_debugplus12 = "press [F] to toggle Coupon (make free)",
            k_debugplus13 = "press [R/C] to destroy/copy card",
            k_debugplus14 = "press [M] to reload atlases",
            k_debugplus15 = "press [UP/DOWN] to cycle rank",
            k_debugplus16 = "press [RIGHT/LEFT] to cycle suit",
            k_debugplus17 = "press [z] plus [1-3] to save a save state",
            k_debugplus18 = "press [x] plus [1-3] to load a save state",
            k_debugplus19 = "Press [H] to isolate background",
            k_debugplus20 = "Press [J] to play splash animation",
            k_debugplus21 = "Press [8] to toggle cursor",
            k_debugplus22 = "Press [9] to toggle all tooltips",
            k_debugplus23 = "+1 Round",
            k_debugplus24 = "+1 Ante",
            k_debugplus25 = "+1 Hand",
            k_debugplus26 = "+1 Discard",
            k_debugplus27 = "Boss Reroll",
            k_debugplus28 = "Background",
            k_debugplus29 = "Win Blind",
            k_debugplus30 = "Double Tag",
            k_debugplus31 = "+10 chips",
            k_debugplus32 = "+10 mult",
            k_debugplus33 = "X2 chips",
            k_debugplus34 = "X10 mult",
            k_debugplus35 = "Win this Run",
            k_debugplus36 = "Lose this Run",
            k_debugplus37 = "Reset",
            k_debugplus38 = "Jimbo",
            k_debugplus39 = "Jimbo talk",
        },
    },
}
