return {
    misc={
        dictionary = {
            k_debugplus1 = "处于收藏界面时，将鼠标悬浮于卡牌上",
            k_debugplus2 = "并按下列键即可实现对应效果:",
            k_debugplus3 = "按[1]键解锁",
            k_debugplus4 = "按[2]键发现",
            k_debugplus5 = "按[3]键生成",
            k_debugplus6 = "当鼠标悬浮于小丑或游戏牌上时:",
            k_debugplus7 = "且同时按住Ctrl(可以在模组设置中禁用)和",
            k_debugplus8 = "[Q]键切换版本效果",
            k_debugplus9 = "[W]键切换增强效果",
            k_debugplus10 = "[E]键切换蜡封",
            k_debugplus11 = "[A/S/D]键分别添加永恒/易腐/租赁",
            k_debugplus12 = "[F]键商品免费",
            k_debugplus13 = "[R/C]键摧毁或复制卡牌",
            k_debugplus14 = "[M]键重新加载图片文件",
            k_debugplus15 = "[上/下方向键]切换点数",
            k_debugplus16 = "[右/左方向键]切换花色",
            k_debugplus17 = "同时按住[Z]和[1-3]根据不同键位进行存档",
            k_debugplus18 = "同时按住[X]和[1-3]根据不同键位进行读档",
            k_debugplus19 = "按[H]键隐藏界面",
            k_debugplus20 = "按[J]键播放动画",
            k_debugplus21 = "按[8]键隐藏光标",
            k_debugplus22 = "按[9]切换所有工具提示",
            k_debugplus23 = "+1 回合",
            k_debugplus24 = "+1 底注",
            k_debugplus25 = "+1 出牌",
            k_debugplus26 = "+1 弃牌",
            k_debugplus27 = "Boss重掷",
            k_debugplus28 = "背景切换",
            k_debugplus29 = "盲注取胜",
            k_debugplus30 = "双倍标签",
            k_debugplus31 = "+10 筹码",
            k_debugplus32 = "+10 倍率",
            k_debugplus33 = "X2 筹码",
            k_debugplus34 = "X10 倍率",
            k_debugplus35 = "直接胜利",
            k_debugplus36 = "快速输掉",
            k_debugplus37 = "清空筹码倍率",
            k_debugplus38 = "召唤金宝",
            k_debugplus39 = "金宝说话",
        },
    },
}
